# SQL Interview Questions  - Quiz

## Introduction

In this lesson, we'll go through a short quiz containing the types of questions about SQL and relational databases that you can expect to see in an interview. 



## SQL Interview Questions

This quiz contains questions on topics you can expect to see in an interview pertaining to SQL and Relational Databases. Some of them are multiple choice, while some are short answer. For these short answer questions, double click on the Jupyter Notebook and type your answer below the line. 

## Question 1

what are the 4 main datatypes in SQLite3? Can we use other common types from other kinds of SQL?

Type your answer below this line: 
The 4 main datatypes in SQLite3 are: NULL, INTEGER, REAL, and TEXT
_______________________________________________________________________________________________________________________________





## Question 2

Explain the relationship between **Primary Keys** and **Foreign Keys**.

Type your answer below this line:
A primary key-foreign key relationship defines a one-to-many relationship between two tables. A foreign key is primary to different table 
_______________________________________________________________________________________________________________________________





## Question 3

Explain the different types of relationships entities can have in a SQL database. 

Type your answer below this line:
1. One-to-One relationship is defined a relationship between two tables where a row from one table can have one and one only matching row in another table.
2. A One-to-Many relationship is defined as a relationship between two tables where a row from one table can have multiple matching rows in another table.
3. A many-to-many relationship refers to a relationship between tables in a database when a parent row in one table contains several child rows in the second table, and vice versa.
_______________________________________________________________________________________________________________________________


## Question 4

Explain the various types of JOINs possible with SQL. 

Type your answer below this line:
1. Inner join
2. Left join
3. Right join
4. Left anti-join
5. Right anti-join
6. Anti-join
_______________________________________________________________________________________________________________________________



## Question 5

Explain the relationship between Aggregate functions and GROUP BY statements.

Type your answer below this line:
Aggregate functions often need an added GROUP BY statement. The GROUP BY statement is used in conjunction with the aggregate functions to group the result-set by one or more columns.

_______________________________________________________________________________________________________________________________



## Question 6

What role do Associative Entities play (JOIN Tables) in many-to-many JOINs?


Type your answer below this line:
The event or transaction having its own set of attributes and characteristics that links the two entities in many-to-many relationships is called an associative entity. 
_______________________________________________________________________________________________________________________________



## Summary

In this lesson, we practiced answering open-ended interview questions for SQL and Relational Databases.